### ISSUE TITLE
Suggestion: Don't imitate browser requests

### ISSUE THREAD

**Issue by purerosefallen** [anlen123/nonebot_plugin_ygo#1]
This is Nanahira, a lover of OneBot, and also a member of [MyCard](https://mycard.moe), the team built the current YGOPro online environment.
Recently we saw this plugin requesting [YGOCDB](https://ygocdb.com), the Yu-gi-oh card query platform, with headers imitating browser requests. The related code could be seen below.
https://github.com/anlen123/nonebot_plugin_ygo/blob/main/nonebot_plugin_ygo/__init__.py#L32

We are very glad to see YGOPro lovers building such bot applications providing group members card query service, and feel good to provide APIs for those bots. However, requests imitating themselves from browser would confuse the trafic analysis system on our side, which makes us into trouble.

Could you take a little time, change the `User-Agent` header into something like `nonebot`, `nonebot2`, or `nonebot-plugin-ygo`? This helps us identify server traffic and reduce server cost, providing better services to both YGOPro community and nonebot community. We would be very appreciated if you could make this change.

**Comment by mercury233** [comment]
just use the API:
https://ygocdb.com/api/v0/?search=%E5%92%95

**Comment by anlen123** [comment]
抱歉，给你们带来了困扰，我也是一个游戏王爱好者，也是一个程序员，以便在群里给群员交流卡片又因为这个平台的搜索结果太过给力，所以采用了，我尽快修改内容，希望萌卡越做越好(敕命好死)。

**Comment by purerosefallen** [comment]
Thanks for your cooperation.
In addition, we would also like to invite you to join MyCard team if you wish to. If you are interested you may send me an email at nanahira@momobako.com
