### ISSUE TITLE
插件无法正常使用

### ISSUE THREAD

**Issue by NSQX13579** [anlen123/nonebot_plugin_ygo#3]
配置项按照文档正常配置了，gocq也正常，但无论搜索哪个卡名都会出现这样的报错
![C(A)Q~V1`@}`30`OVUFX3LM](https://user-images.githubusercontent.com/102937666/177035275-f5bf7524-c443-4208-8733-22b4a144b2aa.png)

**Comment by anlen123** [comment]
我是用没问题的哦，看你的报错信息，应该是信息发送超时了。你可以尝试自己修改源码看看。
