### ISSUE TITLE
群聊调用时出现了报错

### ISSUE THREAD

**Issue by Ctumille** [anlen123/nonebot_plugin_ygo#7]
如题，私聊时不会有影响，试图阅读源码但是最后对群聊如何调用接口部分感到困惑，无法自己解决，特此求助。
错误截图：
![错误ActionFailed](https://github.com/anlen123/nonebot_plugin_ygo/assets/7392476/8b4f657d-35f4-4256-af15-08ae0e0e7941)

**Comment by anlen123** [comment]
有可能是版本问题吧，你看看新版本的群聊接口是怎样的修改一下呢。 或者看看是不是qq群聊被风控了

**Comment by Ctumille** [comment]
> 有可能是版本问题吧，你看看新版本的群聊接口是怎样的修改一下呢。 或者看看是不是qq群聊被风控了

主要可能是因为go-cqhttp挂了所以我换了OpenShamrock的缘故，群聊没有被风控，其他的插件也能用，主要是群聊接口调用不太会改所以想请大佬帮忙看一眼，不知道这个最底下这个“非Json Array对象”的问题有没有可参考的类似问题

**Comment by anlen123** [comment]
应该是gocq才有这个群聊发送接口的, 你换了登录软件的话, 估计是接口失效了, 你换成官方接口重新写一个就行了, 没有非必要用这个群聊接口

**Comment by Ctumille** [comment]
> 应该是gocq才有这个群聊发送接口的, 你换了登录软件的话, 估计是接口失效了, 你换成官方接口重新写一个就行了, 没有非必要用这个群聊接口

这样吗，那我去试试，谢谢大佬的帮助
